### ISSUE TITLE
OO

### ISSUE THREAD

**Issue by cathleruste** [mcodutti/Logique1-Syllabus#11]
-    Les noms des paramètres seront différents de ceux des attributs (on préconisera d’imaginer des noms variés tels que uneDate, maDate, laListe, autreObjet…)
-    Pas d'appel d'un constructeur d'une classe A dans un autre constructeur de cette même classe A. Nous limiterons d'ailleurs au maximum le nombre de constructeurs dans une classe.
-    On peut appeler un setter dans un constructeur. Une remarque sera _peut-être_ ajoutée dans le syllabus par rapport au Java.
-    Il n'y a pas d'initialisation par défaut, y compris pour les objets (cfr un des exo Chaine ou Personne où le constructeur n'initialise pas un des attributs). Il faudrait un exemple où l’initialisation est ‘rien’.
-    Le nom des objets sera différent de celui de la classe, la seule distinction par l'utilisation de la majuscule pour la classe et la minuscule pour l'objet risquant de porter à confusion.
-   exemple OO : on reprendra l'exemple de java : la classe Etudiant (avec attributs divers, cotes d’interro, doubleur ou pas…) ; un deuxième exemple peut être donné avec le moment.

**Comment by mcodutti** [comment]
Si on reprend le même exemple qu'en Java, c'est pas un moins pour les étudiants qui auront un exemple de moins ?

**Comment by cathleruste** [comment]
Je pense aussi mais l'idée venait de toi... ^^

**Comment by cuv** [comment]
Et pourquoi pas un exemple d'article de magasin (numéro, libellé, prix achat, prix vente htva, tva, qte en stock...) C'est simple à comprendre et permet plein d'exercices (calcul du bénéfice, du prix de vente, affichage d'un ticket de caisse, commande des articles en rupture de stock,....)

**Comment by cathleruste** [comment]
Ok. Ce que tu proposes est un "double exemple" : Article + GestionStock. J'essaie d'intégrer ça :)
