### ISSUE TITLE
Fichiers

### ISSUE THREAD

**Issue by cathleruste** [mcodutti/Logique1-Syllabus#12]
-  fichiers : seulement en procédural ; pas de nom en majuscule (utilisation d’une fonte ‘tt’ pour différencier les noms de variables, les structures peuvent rester en gras) ; tous les passages se font en paramètre : pas de "retourner" d'un fichier ; autoriser d'ouvrir et fermer plusieurs fichiers en une seule instruction.
- utiliser la primitive "écrire" pour les fichiers et "afficher" ailleurs.

**Comment by mcodutti** [comment]
Et pourquoi laisser lire alors ? Il faudrait demander à Cuv, vu que la demande vient d'elle.
On pourrait imaginer un "demander nb" au lieu de 'lire nb".

**Comment by cathleruste** [comment]
Elle disait (en juin toujours) que "écrire" portait à confusion chez les étudiants mais que le "lire" pas et qu'il n'était donc pas nécessaire de le remplacer.

**Comment by cathleruste** [comment]
Réponse de Gene : 
Pourquoi changer le "écrire" en "afficher"?: En BDO, les étudiants confondent le "écrire" sans fichier en paramètre qui écrit sur la sortie standard et l'"écrire" avec en paramètre un fichier. Nous avons moins le problème avec "lire" car dans ce cours nous lisons presque que sur fichier.
Soit on change "écrire" par "afficher" soit on rend le paramètre "nomDuFichier" obligatoire ce qui donne par exemple "écrire SYSTEM_OUT,..." Cette deuxième solution a le mérite de pouvoir être symétrique pour le "lire" et de bien faire remarquer que afficher et écrire sont identiques au paramètre fichier près.
Qu'en pensez-vous?

J'avais proposé de faire le chapitre "fichiers". La proposition tiens toujours. Pour quand doit-il être terminé?

**Comment by mcodutti** [comment]
Je trouve l'ajout du SYSTEM_IN/OUT) lourd car dans 95% des cas on fait une lecture/écriture hors fichier.

Je ne comprends toujours pas pourquoi ce qui se passe dans leurs têtes qui fait qu'ils font la confusion pour l'écriture et pas pour la lecture; bizarre...

Gene, tu peux relire le chapitre sur les fichiers; je pense que les changements envisagés ont étés appliqués: plus de notation OO.

**Comment by cathleruste** [comment]
13.7.8 : manque les accolades aux 2 énum.
