### ISSUE TITLE
Primitives pour les chaines et les caractères

### ISSUE THREAD

**Issue by mcodutti** [mcodutti/Logique1-Syllabus#18]
Le syllabus propose peu d'exercices avec des chaines et des caractères.
Il y en aurait pourtant de chouettes à introduire sur le chiffrement ou l'analyse de textes. À mon avis, c'est en partie parce qu'on manque d'outils pour les manipuler.
Ainsi, l'exercice sur les palindromes doit introduire quelques primitives comme estLettre().

Ce serait bien de proposer un ensemble cohérent de modules utiles qu'on peut utiliser avec tous les exercices sur les chaines et les caractères. À mettre dans le chapitre 3 quand on introduit les types et à reprendre dans l'aide mémoire en annexe.

Par exemple
Pour les chaines
- long(s) -> entier // donne la taille de s
- car(s,p) -> caractère // donne le caractère en position p (à partir de 1) dans s
- concat(s1,s2) -> chaine // concatène s1 et s1

Pour les caractères
- chaine(c) -> chaine // transforme un caractère en chaine de taille 1
- estLettre(c) -> booléen // dit si le caractère est une lettre 
- idem pour estChiffre, estMajuscule, estMinuscule
- majuscule(c) -> caractère // donne la majuscule de la lettre
- idem pour minuscule
- numLettre(c) -> entier // donne la position de la lettre dans l'alphabet (ex: 'C' donne 3)
- lettre(num) -> caractère // l'inverse de la précédente (ex: 4 donne 'D')

**Comment by mcodutti** [comment]
Bon, je l'ai fait.
Ajout des sections 3.4.7 et 3.4.8
Ajout de deux exercices dans le chapitre sur les boucles
Ajout d'un exercice dans le chapitre sur les tableaux (le tout lié au chiffre de César)

**Comment by cuv** [comment]
boucles; exercice 24 s/On vout/On vous/
tableaux; exercice 19 s/??/24/

**Comment by mcodutti** [comment]
boucles : corrigé
tableaux : rien à chnager. Les ?? sont là pour une référence. Nécessite 2 compilations pour que ce soit juste.
