### ISSUE TITLE
Lignes longues dans un algorithme

### ISSUE THREAD

**Issue by mcodutti** [mcodutti/Logique1-Syllabus#19]
Comment techniquement couper une ligne trop longue dans un algorithme (cf. par exemple les algorithmes sur les ruptures avec des tant que à rallonge).

Voir dans le manuel du package utilisé (algpseudocode) si c'est déjà prévu

**Comment by cathleruste** [comment]
À tester (mais pas ce soir ;) : http://fr.softuses.com/65950

**Comment by mcodutti** [comment]
http://fr.softuses.com/65950 ne me convient pas :(
J'ai aussi essayé çà : http://tex.stackexchange.com/questions/68539/adjust-the-indentation-whithin-the-algorithmicx-package-when-a-line-is-broken mais c'est pas mieux. En gros, il y a 2 problèmes : 
- Les lignes verticales (qui sont un ajout non standard) commencent à déconner
- On ne choisit pas où on coupe et c'est moins lisible

Mais tout çà m'a donné des idées pour ma propre solution. La voici.
1) Si c'est une ligne simple, on passe à la ligne et on utilise la commande \Suite qui crée une indentation. Ex:

```
    \Write cpt, «~étudiant dans l’option~», saveOption, 
        \Suite «~sont nés en~», saveAnneeNaissance
```

2) Si c'est un début de bloc (if, while, module, ...), j'ai créé un bloc "custom". Il y a un début, une fin, une indentation mais aucun texte prédéfini. Ex : 

```
    \Custom \algorithmicwhile\ début du test
        \Suite fin du test \algorithmicdo
        \LComment du code ici
    \EndCustom \algorithmicend\ \algorithmicwhile
```

cf. le fichier algoesi.sty pour une liste des \algorithmic... qui existent (assez intuitif)
