### ISSUE TITLE
compiler tex -> pdf

### ISSUE THREAD

**Issue by cuv** [mcodutti/Logique1-Syllabus#20]
Premier pas sur GitHub et très vague souvenir de latex...
Répertoire "logique1-Syllabus-master" transféré sur mon PC, première exécution  de la commande "pdflatex log1.tex" dans ce même répertoire. Voici les erreurs reçues:

! LaTeX Error: File `algpseudocode.sty' not found.
! LaTeX Error: File`algorithm.sty' not found.
! Undefined control sequence.
l.31 \algdef
            {SE}[WHILE]{While}{EndWhile}[1]

A l'aide !

**Comment by mcodutti** [comment]
Chez moi (Ubuntu), les styles manquants se trouvent dans le package 'texlive-science'.

**Comment by cuv** [comment]
merci tout est ok!

**Comment by mcodutti** [comment]
Super, je ferme l'issue :)
