### ISSUE TITLE
Ch 3 algorithmes séquentiels

### ISSUE THREAD

**Issue by cuv** [mcodutti/Logique1-Syllabus#21]
3.3 .3 lire, écrire, pour,... changer écrire en afficher 
3.6 Dans les remarques, inverser écrire et afficher.
3.9.2 J'ajouterais au moins un exemple d'utilisation. Dans "Lien avec les entiers" on fait référence à un exemple qui n'est pas donné. (dû à un déplacement "sauvage" de ce § ;-) )

**Comment by cathleruste** [comment]
Geneviève, peux-tu vérifier que l'exemple est suffisamment clair (et si tu en as un autre moins bateau, je prends !)

**Comment by cuv** [comment]
J'aime bien ton exemple bateau :-)
