### ISSUE TITLE
ch 7 Les boucles

### ISSUE THREAD

**Issue by cuv** [mcodutti/Logique1-Syllabus#25]
7.3.3 l'indice de boucle nb n'est pas déclaré dans le dernier exemple.

fin du 7.3.3 Dans l'exemple l'indice de boucle est nb et dans la dernière remarque on dit qu'elle se nomme souvent i....;-)
exemple 5 : je retournerais la somme plutôt que de l'afficher. 
L'indice de boucle nb n'est pas déclaré mais la variable i n'est pas utilisée. 

Dans les exercices on demande presque tjs d'afficher le résultat. Si possible je demanderais de le retourner.
Exercice 21: en demandant le pourcentage d'obèses on simplifie le problème, plus besoin de savoir s'ils sont maigres ou normaux. C'est voulu?

**Comment by mcodutti** [comment]
Pour l'ex.21, j'imagine que c'est voulu afin de se concentrer sur les boucles et éviter plein de tests.
C'est aussi un bon exemple où il y a trop d'infos dans l'énoncé.
Enfin, je suppose... c'est pas mon énoncé au départ ;)
