### ISSUE TITLE
ch tableaux à 2 dim

### ISSUE THREAD

**Issue by cuv** [mcodutti/Logique1-Syllabus#28]
Dans ce chapitre il n'y a aucun exemple: c'est fort peu ;-)

**Comment by mcodutti** [comment]
Mais j'en ai mis beaucoup dans la nouvelle annexe (parcours des tableaux).
Est-ce qu'il faudrait en intégrer dans le chapitre ? Trouver d'autres exemples ?

**Comment by cuv** [comment]
Je pense que mettre, comme dans les autres chapitres, un ou deux exemples dans le chapitre serait bien. Tu peux en plus renvoyer à l'annexe.

**Comment by cathleruste** [comment]
Ajout d'un exemple à partir de celui du tab1D
