### ISSUE TITLE
De beaux algorithmes

### ISSUE THREAD

**Issue by mcodutti** [mcodutti/Logique1-Syllabus#3]
Utiliser et configurer un package d'édition d'algorithmes pour avoir qqchose de beau et qui ressemble le plus possible à ce qu'on avait.

**Comment by cathleruste** [comment]
Il me semble que tu avais proposé quelque chose à ce sujet vendredi, non ?
C'était ça : http://algorithms.berlios.de/ ?

**Comment by mcodutti** [comment]
J'ai plutôt choisi algorithmicx : http://www.ctan.org/pkg/algorithmicx
Je t'envoie par mail la version actuelle du syllabus.
Les 1er chapitres ont été retravaillés et montrent à quoi ressemblent les
algorithmes.

2013/6/25 cathleruste notifications@github.com

**Comment by mcodutti** [comment]
Bon, il me semble que j'ai maintenant tout ce qu'il faut pour faire de beaux algorithmes.
Les explications sont dans le fichier MANUEL-ALGO.txt
