### ISSUE TITLE
Mise à jour de la liste des profs

### ISSUE THREAD

**Issue by mcodutti** [mcodutti/Logique1-Syllabus#37]
La liste des profs sur la page de garde n'est pas la bonne.
Si qqun la connait...
Je commence avec les plus évidents : CLR, CUV, LBC, MCD, NPX

**Comment by cathleruste** [comment]
Faut retirer Moussa et ajouter les acronymes des 2 nouveaux :)

**Comment by lbeeckmans** [comment]
Voici une liste exhaustive : 

LBC, CLR, CUV, DWI, ELV, HAL, MCD, NPX, JDS, SRV

JDS = Jérôme Dossogne
SRV = Frédéric Servais

**Comment by lbeeckmans** [comment]
Au fait, pourquoi met-on cette liste au début? Ce qui me gène un peu, c'est l'absence totale de notion de droit d'auteur avec ce nouveau système, comme si les noms qu'on voit sur la page de garde ont tous collaboré de manière significative à l'écriture du syllabus.

Pour rendre à César ce qui lui appartient, ne faudrait-il pas mettre plutôt en 2ème page un petit texte historique du genre : "cet ouvrage a été initié par M. Monbaliu, et modifié peu à peu dans la version actuelle par Messieurs et Mesdames . X et Y...". Où considère-t-on qu'il s'agit d'une contribution de groupe ou chacun oeuvre dans l'anonymat? Dans ce cas je préfèrerais encore qu'on ne mette aucun nom, ou qu'on indique alors "Cours enseigné par : [liste des profs]".

**Comment by mcodutti** [comment]
Je pense que mettre un historique serait sympa mais je ne connais pas toute l'histoire du document.
Et ok pour le "cours enseigné par..."

**Comment by mcodutti** [comment]
Nom des profs : ok.
Historique : j'ai écrit une petite phrase bateau de remerciement sans citer de noms. Si qqun se sent d'écrire plus...

**Comment by mcodutti** [comment]
Laurent a ressorti un syllabus de 2001 ce qui m'a permis d'être plus précis.
