### ISSUE TITLE
OO : exemple article - exercice stock

### ISSUE THREAD

**Issue by cuv** [mcodutti/Logique1-Syllabus#38]
Pour l'exemple article, je pense que l'on fixe le prix de vente (5.99€) plutôt que de le calculer. 
Pour l'exercice stock, j'avais pas pensé qu'ils n'avaient pas vu les listes à ce moment. x-) Donc j'imagine que tu attends un tableau d'articles. Mais pour avoir par exemple les articles en rupture de stock, tu attends aussi un tableau ou tu affiches les articles?  Sans liste, je le sens moins bien....

**Comment by cathleruste** [comment]
À ce stade là, j'afficherais simplement les articles du tableau dont la quantité est 0.
