### ISSUE TITLE
Les boucles 

### ISSUE THREAD

**Issue by cathleruste** [mcodutti/Logique1-Syllabus#40]
Adapter l'exo 22 Cotes avec les contraintes actuelles

**Comment by cathleruste** [comment]
Le chiffre de César : sans les tableaux, c'est loooong ^^

**Comment by mcodutti** [comment]
J'ai mis une solution pour le chiffre de César (je sais tout le monde pourrait la voir).
C'est quand même pas si long.

**Comment by cathleruste** [comment]
J'avais oublié le numLettre. Alors, ok :)
