### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by cathleruste** [mcodutti/Logique1-Syllabus#41]
On n'ajouterait pas le planning au début du syllabus ?

**Comment by lbeeckmans** [comment]
Est-ce vraiment utile pour les étudiants? Le fait de le montrer à tout le monde peut être contraignant. Si on dit au début de l'année qu'on voit les chapitres 1-11 au 1er quadrimestre et les chapitres 12-15 au 2nd, n'ont-ils pas toute l'information utile?
