### ISSUE TITLE
Sauts de page

### ISSUE THREAD

**Issue by cathleruste** [mcodutti/Logique1-Syllabus#5]
À vérifier.

**Comment by mcodutti** [comment]
Je dois encore voir comment mieux spécifier à LaTeX que certains morceaux
ne devraient pas être coupés.
Sinon, il faudra repasser à la main :(

2013/6/26 cathleruste notifications@github.com

**Comment by cathleruste** [comment]
http://tex.stackexchange.com/questions/69667/how-can-one-keep-a-section-from-being-at-the-end-of-a-page

**Comment by mcodutti** [comment]
J'avais le problème car certains titres étaient logiquement des titres mais n'utilisaient pas les balises adhoc (...section). En partie du à la traduction automatique, en partie à cause de mes macros.
Je pense que c'est bon maintenant.
