### ISSUE TITLE
Un étudiant publie les solutions sur github

### ISSUE THREAD

**Issue by npettiaux** [mcodutti/Logique1-Syllabus#63]
Un étudiant de Marco publie ses solutions sur github, en reprenant le modèle de Marco. Donc c'est jolie aussi. Voir https://github.com/Astalaseven/Log1-correction

Dans l'état, nous n'avons à mon avis rien à dire. L'étudiant fait ce qu'il veut (et c'est une bon exercice pour lui). J'aimerais que les autres fassent de même pour qu'ils puissent tous se corriger les uns les autres (nous jouons alors juste arbitre ;-) et que ceux qui viennent après trouvent **beaucoup** de code pour s'inspirer.

**Comment by mcodutti** [comment]
Ca, c'est ce que TU penses et pas ce que JE pense, tu le sais bien.
Qu'ils trouvent beaucoup de code, très bien.
Mais ceux des exercices qu'on donne, ça ne me plait pas du tout.
Et pondre de nouveaux exercices chaque année ne me plait pas non plus.

**Comment by npettiaux** [comment]
Comme PBT l'a écrit sur fora, de toute façon nous n'avons rien à dire sur ce que les étudiants sont en dehors du cours et publient sur internet (en libre ou non). C'est donc AMHA un combat qu'il ne faut pas mener.  Pour devoir pondre des exercices nouveaux chaque année, il n'est pas très difficile d'en avoir beaucoup. On pourrait aussi demander aux étudiants de nous aider à trouver des énoncés. (et nous trions les bons et les moins bons selon nos critères).

**Comment by cathleruste** [comment]
Dans mon souvenir, nous avons déjà eu cette discussion, il y a tout juste un an, dans le bureau de Claude.
La version officielle est claire : nous ne pouvons pas l'empêcher mais nous ne soutenons pas ce genre initiative. Je m'en tiendrai donc à cette version.
Je tiens aussi à signaler que les exercices du syllabus ont été construits au fur et à mesure des années, leur difficulté est croissante. Les refaire intelligemment chaque année est un boulot énorme dans lequel je refuse de m'investir.

**Comment by mcodutti** [comment]
Je ne suis pas d'accord avec Nicolas.
Nous ne pouvons rien imposer, mais nous pouvons expliquer et convaincre.
Quant à pondre de nouveaux exercices chaque année, tu surestimes :
- la capacité de travail du groupe. Si tu dis aujourd'hui : "l'année prochaine on change tous les exercices", 
  je peux te garantir que ce ne sera pas fait. Même si les étudiants participent.
- la possibilité de trouver des exercices simples toujours différents.

**Comment by npettiaux** [comment]
Je suis (de suivre) la position officielle discutée. Pas de doute là dessus. Je sais bien que tu as raison Catherine : " Les refaire intelligemment chaque année est un boulot énorme". Moi aussi je refuse de m'investir dans une réécriture complète. Je veux bien proposer des variantes.
Marco, je ne propose pas du tout de changer tous les exercices. Juste en rajouter si ceux proposés ont des solutions en ligne (de toutes façons ces solutions existent dans les pompes des élèves, autant qu'elles soient en ligne où nous pouvons faire éventuellement des commentaires si il y a trop d'erreurs). Je ne susrestime pas la difficulté. Je sais que ce sera fort difficile. Je pense simplement qu'on peut progressivement rajouter des exercices, par exemple des variantes. Et oui, je sais que trouver des motivés pour faire des propositions sera difficile, et qu'il n'y en aura pas beaucoup. D'où l'idée d'ouvrir le nombre de personnes pouvant faire des propositions.

**Comment by Astalaseven** [comment]
Bonjour,

Je me permets d’intervenir pour signaler que le dossier contenant les réponses a été passé en privé (M. Codutti m’a expliqué la raison pour laquelle il préfère que les solutions ne soient pas disponibles trop facilement sur Internet). J’ai aussi vu la réaction de certains qui se moquaient presque de l’assistant de TD car ils avaient trouvé les énoncés et certaines réponses d’un TD sur Internet… Personnellement ça ne change pas grand-chose pour moi, je les postais surtout sur github pour garder une trace facilement accessible de partout.

Ce qui pourrait être intéressant serait d’utiliser les réponses des étudiants pour faire des exemples, ou présenter des bouts de code qui sont pensés autrement et qui peuvent inspirer pour de futurs exercices.
(par exemple l’utilisation de XOR pour changer le contenu de deux variables, c’est original même si plus complexe à comprendre…)

Les personnes ayant accès au dossier privé sont listées ici : EDIT url rien à voir
Les personnes sont listées dans https://github.com/Astalaseven/Log1-correction/watchers et ici : https://github.com/Astalaseven/Log1-correction/settings/collaboration mais je suis le seul à y avoir accès à mon avis…
