### ISSUE TITLE
Structures - Logo Java sur exercice Cercle plutôt que Rectangle

### ISSUE THREAD

**Issue by mcodutti** [mcodutti/Logique1-Syllabus#67]
Des collègues de logique trouvent l'exercice du Rectangle trop compliqué pour l'imposer avec le logo Java (singulièrement le dernier point sur l'intersection de rectangles).

Il est proposé de mettre le logo sur l'exercice du Cercle.

À ne faire qu'en concertation avec l'équipe Java
- Cet exercice est utilisé dans un TD OO en fin janvier
- Ce TD Java contient près de 2 pages de ré-explication du problème et de sa mise en contexte OO. Il faudra trouver un volontaire pour le modifier.

**Comment by cathleruste** [comment]
Ok, je m'y collerai asap.
