### ISSUE TITLE
Ch Données - ex OXO (pardon oscillateur)

### ISSUE THREAD

**Issue by mcodutti** [mcodutti/Logique1-Syllabus#9]
Dans cet exercice, les tableaux ne sont pas bine passés à la conversion automatique.
Les refaire.

**Comment by cathleruste** [comment]
Pas trouvé d'ex OXO dans le chapitre des données :s 
Je n'ai pas terminé ce chapitre, je me suis arrêtée à l'ex sur les Congés :) 
Les tableaux des ex Oscillateur, Vaisseau spatial et Message codé sont encore à faire. Je m'y colle... asap ;)

**Comment by mcodutti** [comment]
Désolé, je voulais bien parlé de l'ex. Oscillateur.
Message codé, je l'ai fait :)

**Comment by cathleruste** [comment]
Tu as déjà refais la fin ? (pcq là, je viens de commencer :))

**Comment by mcodutti** [comment]
Ben oui !

2013/7/22 cathleruste notifications@github.com

**Comment by cathleruste** [comment]
Hé, je n'ai plus l'habitude de regarder si qq1 d'autre a bossé ^^ ;)

**Comment by mcodutti** [comment]
J'ai un peu de temps aujourd'hui.
Ca te va si je le fais moi ?

**Comment by cathleruste** [comment]
Le temps est une denrée extrêmement rare chez moi en ce moment, vas-y si ça te fait plaisir :) Merci!
